### ISSUE TITLE
rule 5.2.15 is mentioned in comments but not implemented

### ISSUE THREAD

**Issue by jorhett** [abuxton/cis_benchmarks#6]
This comment would indicate that 5.2.15 is implemented, but there's nothing in the code to do so

https://github.com/abuxton/cis_benchmarks/blob/master/manifests/redhat7/rule/v_2_1_1/rule_5_2.pp#L16

**Comment by abuxton** [comment]
https://github.com/abuxton/cis_benchmarks/blob/master/manifests/redhat7/rule/v_2_1_1/rule_5_2.pp#L53
explicitly not implemented,  everyone has their own version of ssh rules etc, at time of development it was not worth the Level of effort to implement the default rules for them never to be used.

**Comment by jorhett** [comment]
That's the reply for when `manage_ssh` is disabled. It seems to indicate that 5.2.15 would be implemented if that is enabled, but it's not.

Obviously the user should tune those values for their needs. I think issues like this should be documented more clearly. There's a number of user-must-adjust knobs that are under-documented.
